config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "lines#index"

  resources :calendars
  resources :lines do
    resources :events, shallow: true
    resources :arcs, shallow: true
    resources :entities, shallow: true
  end

end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :calendar
	belongs_to :user
	has_many :events, inverse_of: :line
	accepts_nested_attributes_for :events
	has_many :arcs
	has_many :entities

	validates :name, presence: true
	validates_associated :calendar
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
	before_action :authenticate_user!

	# consider adding accepts_nested_attributes_for :calendar in model
	def index
		@lines = current_user.lines
	end

	def new
		@line = Line.new
		@calendars = current_user.calendars
	end

	def create
		@line = current_user.lines.new(line_params)

		respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Timeline was successfully created.' }
        format.json { render action: 'create', status: :created, location: @line }
        format.js   { render action: 'create', status: :created, location: @line }
      else
        format.json { render json: { model: 'line', error: @line.errors}, status: :unprocessable_entity }
        format.js { render json: { model: 'line', error: @line.errors}, status: :unprocessable_entity }
      end
		end
	end

	def show
		@line = Line.find(params[:id])
		@events = @line.events
		@arcs = @line.arcs
		@entities = @line.entities
		@tags = current_user.tags
		gon.tags = @tags.all.collect(&:name)
		# gon.events = events_jsonify(@events)

		respond_to do |format|
			format.html
			format.json { render json: events_jsonify(@events) }
		end
	end
  
	def destroy
		@line.destroy
	end

	private

		def line_params
			params.require(:line).permit(:name, :calendar_id)
		end

		# TODO security of interpolation?
		def events_jsonify(events)
			events.collect do |event|
				{ id: event.id,
					name: event.name,
					summary: event.summary,
					start_era: event.start_era,
					start_date: "#{event.start_date or 0}/#{event.start_month or 0}/#{event.start_year}",
					end_date: "#{event.end_date or 0}/#{event.end_month or 0}/#{event.end_year or event.start_year}",
					arcs: event.arcs,
					entities: event.entities }
			end.to_json
		end
		
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.haml
.form-container
	= form_for @line, data: {remote: true}, html: {class: "form-sections-container"} do |f|
		%label{class: "form-subsection-heading"} New timeline
		- # = f.label :abbrev
		- # = f.text_field :abbrev
		.form-fieldset
			.field.field-block
				= f.label :name, "Name:"
				= f.text_field :name
			.field.field-inline
				= f.label :calendar_id, "Calendar:"
				= f.collection_select :calendar_id, @calendars, :id, :name 
			.field.field-inline
				- # TODO stackable modal - $("#form-modal").modal("hide")
				= link_to 'New Calendar', new_calendar_path, remote: true
			.button-container
				= f.submit "Create Timeline"

app/views/lines/_new.html.haml
#new-timeline-modal.modal-dialog
	.pure-g.modal-content
		.pure-u-1
			= render partial: 'form'

app/views/lines/_save.js.haml
- if @line.errors.any?
	- @line.errors.each do |message|
		$('input[name=\'timeline[' + "#{ message }" + ']\']').addClass('has-error');
- else
	$("#form-modal").modal("hide")


- # use this instead: https://www.alfajango.com/blog/rails-3-remote-links-and-forms/

app/views/lines/create.js.haml
= render "save"

app/views/lines/index.html.haml
%ul.errors

= link_to 'New Calendar', new_calendar_path, remote: true
= link_to 'New Timeline', new_line_path, remote: true

.timelines-container
	- @lines.each do |line|
		.timeline-thumbnail
			= link_to line.name, line_path(line.id), "data-no-turbolink" => true

#form-modal.modal.fade

app/views/lines/new.js.haml
:plain
	$("#form-modal").html("#{ escape_javascript(render 'new' )}")
	$("#form-modal").modal("show")

app/views/lines/show.html.haml
%svg#timeline

= link_to 'New Event', new_line_event_path(@line.id), remote: true

#form-modal.modal.fade

- # TODO: investigate security issues
:javascript
	window.line_path = '#{j line_path}'